[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rats"
version = "v1.0.1"
description = "Movie Ratings Synchronization with Python"
authors = [{ name = "Sebastian Schreck", email = "sebastian.schreck@stegschreck.de" }]
requires-python = "~=3.10"
readme = "README.md"
license = "AGPL-3.0-only"
dependencies = [
    "beautifulsoup4==4.13.5",
    "bs4==0.0.2",
    "configparser==7.2.0",
    "progressbar2==4.5.0",
    "selenium==4.35.0",
    "xvfbwrapper==0.2.13",
    "requests>=2.32.4,<3",
    "toml>=0.10.2,<0.11",
    "python-decouple~=3.8",
    "hatchling>=1.27.0",
]

[dependency-groups]
dev = [
    "ruff==0.12.12",
    "pydantic==2.11.7",
    "pytest==8.4.1",
    "pytest-cov==6.2.1",
    "pre-commit==4.3.0",
    "types-beautifulsoup4==4.12.0.20250516",
    "types-requests>=2.32.4.20250611,<3",
    "types-toml>=0.10.8.20240310,<0.11",
    "python-semantic-release>=10.2.0,<11",
]

[tool.uv]
package = false

[tool.mypy]
exclude = ['venv']

[tool.semantic_release]
assets = []
build_command_env = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
no_git_verify = false
tag_format = "v{version}"
version_toml = ["pyproject.toml:project.version"]

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
default_bump_level = 0

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false
insecure = false

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true
