[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "rats"
version = "v1.0.1"
description = "Movie Ratings Synchronization with Python"
authors = ["Sebastian Schreck <sebastian.schreck@stegschreck.de>"]
license = "AGPL-3.0-only"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "4.12.3"
bs4 = "0.0.2"
configparser = "7.1.0"
progressbar2 = "4.5.0"
selenium = "4.26.1"
xvfbwrapper = "0.2.9"
requests = "^2.32.3"
toml = "^0.10.2"
python-decouple = "^3.8"

[tool.poetry.group.dev.dependencies]
black = "24.10.0"
pydantic = "2.9.2"
pytest = "8.3.3"
pytest-cov = "6.0.0"
flake8 = "7.1.1"
pre-commit = "4.0.1"
pylint = "3.3.1"
mypy = "1.13.0"
types-beautifulsoup4 = "4.12.0.20241020"
types-requests = "^2.32.0.20241016"
types-toml = "^0.10.8.20240310"
python-semantic-release = "^9.14.0"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    node_nodules
  | \.git
  | \.venv
  | \venv
  | \.mypy_cache
  | build
  | dist
)/
'''

[tool.mypy]
exclude = ['venv']

[tool.semantic_release]
assets = []
build_command_env = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
no_git_verify = false
tag_format = "v{version}"
version_toml = ["pyproject.toml:tool.poetry.version"]

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
default_bump_level = 0

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false
insecure = false

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true

