name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov RatS --cov-report term-missing --cov-report xml
    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        api-token: ${{ secrets.CODACY_API_TOKEN }}
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml
        language: python
      env:
        CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        CODACY_USERNAME: ${{ github.GITHUB_REPOSITORY_OWNER }}
        CODACY_PROJECT_NAME: RatS

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Publish to GitHub Docker Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: stegschreck/rats/rats
        username: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        tag_names: true

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create Release
      if: success() && startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: commits[0][message]
        draft: false
        prerelease: false
